<a href="https://colab.research.google.com/github/LavanyaPobbathi/Lavanya_INFO5731_Fall2023/blob/main/In_class_exercise/Pobbathi_Lavanya_Exercise_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (due on 11:59 PM 10/08/2023, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [1]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

Task Description:
Given a dataset of user reviews for various products, the objective is to classify each review into one of three categories: Positive, Negative, or Neutral sentiment.

Features for the Classification Model:

Bag of Words (BoW):

This is a simple representation where a text is transformed into a vector indicating the frequency of every word in the document.
Why it's useful: A high frequency of certain words (like "love", "amazing", "best") might be indicative of positive sentiment, while others (like "hate", "terrible", "worst") might suggest a negative sentiment.

TF-IDF (Term Frequency-Inverse Document Frequency):

This is a measure of how important a word is to a document in a corpus. Words that appear frequently in one document but not in many documents throughout the corpus get a high TF-IDF score.
Why it's useful: It helps in weighing down the less informative frequent terms in the dataset (like "the", "is", "and") while giving more weight to terms that are discriminative for sentiment.

Sentiment Lexicon Features:

There are predefined lexicons available (like AFINN, SentiWordNet) which provide sentiment scores to words.
Why it's useful: A review with a high cumulative positive score from a sentiment lexicon can be inferred to have a positive sentiment and vice versa.

N-grams:

These are contiguous sequences of n items from a given sample of text. For example, bigrams (2-grams) for the sentence "I love it" are: "I love" and "love it".
Why it's useful: Often sentiment is conveyed not by individual words but by phrases. For example, "not good" has a different sentiment than the individual words "not" and "good".

Part-of-Speech (POS) Tagging:

This involves labeling words in a sentence as nouns, verbs, adjectives, etc.
Why it's useful: Adjectives and adverbs are often strong indicators of sentiment. For example, words like "beautiful", "lovely", "poorly", "horribly" etc.

Embeddings (like Word2Vec, GloVe, etc.):

These convert words into dense vectors of fixed size that are trained to capture the semantic meaning of the word.
Why it's useful: Semantically similar words are close in the embedding space. This means words like "awesome" and "fantastic" might have vectors pointing in similar directions, which can be useful for sentiment analysis.

Document Length:

This is a feature indicating the number of words in a review.
Why it's useful: Extremely short reviews might be less informative or neutral compared to longer, detailed reviews which might strongly convey sentiment.

Punctuation and Capitalization:

Count or presence of exclamation marks, question marks, and the use of ALL CAPS.
Why it's useful: Excessive use of exclamation marks or writing in ALL CAPS might indicate strong sentiment, either positive ("LOVE THIS!!!") or negative ("WORST PRODUCT EVER!!!").

Emojis:

Extract and classify emojis present in the text.
Why it's useful: Emojis can be strong indicators of sentiment. 🙂 might indicate positive sentiment while 😡 indicates negative.

Negation Handling:

Detection of negation words like "not", "never", "isn't".
Why it's useful: Negations can reverse the sentiment of a phrase. "good" is positive, but "not good" is negative.
Using a combination of these features can significantly improve the performance of the classification model, as they provide a comprehensive representation of the text data and capture different aspects of sentiment.




'''

'\nPlease write you answer here:\n\nTask Description:\nGiven a dataset of user reviews for various products, the objective is to classify each review into one of three categories: Positive, Negative, or Neutral sentiment.\n\nFeatures for the Classification Model:\nBag of Words (BoW):\n\nThis is a simple representation where a text is transformed into a vector indicating the frequency of every word in the document.\nWhy it\'s useful: A high frequency of certain words (like "love", "amazing", "best") might be indicative of positive sentiment, while others (like "hate", "terrible", "worst") might suggest a negative sentiment.\nTF-IDF (Term Frequency-Inverse Document Frequency):\n\nThis is a measure of how important a word is to a document in a corpus. Words that appear frequently in one document but not in many documents throughout the corpus get a high TF-IDF score.\nWhy it\'s useful: It helps in weighing down the less informative frequent terms in the dataset (like "the", "is", "and") w

Question 2 (10 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [3]:
import nltk
nltk.download('vader_lexicon')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [7]:
# You code here (Please add comments in the code):

import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.tokenize import word_tokenize
from nltk.util import ngrams
from collections import Counter

# Sample text data
reviews = [
    "Introducing the Graph of Thoughts (GoT): a cutting-edge framework that elevates the prompting capabilities of large language models (LLMs) beyond established paradigms",
    "like Chain-of-Thought or Tree of Thoughts (ToT). GoT's primary innovation lies in its unique ability to represent LLM-generated information as an intricate, unrestricted graph",
    "Here, individual units of information, referred to as 'LLM thoughts,' serve as vertices interconnected by edges, symbolizing the intricate dependencies between them.",
    "This novel approach empowers us to harmoniously blend various LLM thoughts, distilling the essence of complex thought networks, and amplifying ideas through feedback loops. ",
    "GoT showcases its superiority over existing methodologies by significantly enhancing sorting quality by 62% compared to ToT, while concurrently reducing costs by over 31%.",
    "Moreover, GoT has been meticulously designed for extensibility, accommodating the integration of fresh thought transformations",
    "This groundbreaking approach empowers us to harmoniously blend various LLM thoughts, distilling the very essence of complex thought networks, and amplifying ideas through feedback loops, creating a sense of awe and astonishment.🙂 ",
    "Making it an avant-garde platform for pioneering new prompting strategies🙂. This research aims to bridge the gap between LLM reasoning and human thought processes, mirroring the intricate networks observed in phenomena like brain mechanisms and recurrence.",
]

# 1. Bag of Words
vectorizer_bow = CountVectorizer()
bow = vectorizer_bow.fit_transform(reviews).toarray()

# 2. TF-IDF
vectorizer_tfidf = TfidfVectorizer()
tfidf = vectorizer_tfidf.fit_transform(reviews).toarray()

# 3. Sentiment Lexicon Features
sia = SentimentIntensityAnalyzer()
sentiment_scores = [sia.polarity_scores(review) for review in reviews]

# 4. N-grams (Using Bigrams as an example)
vectorizer_bigram = CountVectorizer(ngram_range=(2, 2))
bigrams = vectorizer_bigram.fit_transform(reviews).toarray()

# 5. Part-of-Speech Tagging
reviews_tokenized = [word_tokenize(review) for review in reviews]
pos_tags = [nltk.pos_tag(review) for review in reviews_tokenized]

# 6. Document Length
doc_lengths = [len(review.split()) for review in reviews]

# 7. Punctuation and Capitalization
exclamations = [review.count('!') for review in reviews]
all_caps = [sum(1 for word in review.split() if word.isupper() and len(word) > 1) for review in reviews]

# 8. Emojis
emojis = ['🙂', '😡']  # Sample set of emojis for this example
emoji_counts = [{emoji: review.count(emoji) for emoji in emojis} for review in reviews]

# 9. Negation Handling
negations = ["not", "never", "isn't", "wasn't", "couldn't"]
negation_counts = [sum(review.count(neg) for neg in negations) for review in reviews]

# Print the extracted features for demonstration
print("Bag of Words:", bow)
print("\nTF-IDF:", tfidf)
print("\nSentiment Scores:", sentiment_scores)
print("\nBigrams:", bigrams)
print("\nPOS Tags:", pos_tags)
print("\nDocument Lengths:", doc_lengths)
print("\nExclamation Counts:", exclamations)
print("\nAll Caps Counts:", all_caps)
print("\nEmoji Counts:", emoji_counts)
print("\nNegation Counts:", negation_counts)


Bag of Words: [[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]

TF-IDF: [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.22508772 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.23689757 0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.21609499 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

Sentiment Scores: [{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}, {'neg': 0.091, 'neu': 0.617, 'pos': 0.292, 'compound': 0.6369}, {'neg': 0.0, 'neu': 0.929, 'pos': 0.071, 'compound': 0.1531}, {'neg': 0.0, 'neu': 0.809, 'pos': 0.191, 'compound': 0.6369}, {'neg': 0.0, 'neu': 0.906, 'pos': 0.094, 'compound': 0.34}, {'neg': 0.0, 'neu': 0.859, 'pos': 0.141, 'compound': 0.3182}, {'neg': 0.0, 'neu': 0.85, 'p

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_selection import mutual_info_classif
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

# Sample text data
text_data = [
    "This Special Issue of the IEEE Transactions on Plasma Science (TPS) follows the first American Physical Society Division of Plasma Physics (APS-DPP) mini-conference on Machine Learning, Data Science, and Artificial Intelligence in Plasma Research held during the 60th APS-DPP Meeting in Portland, OR, USA (November 5–9, 2018).",
    "It contains selected highlights from not only the mini-conference but also the broader plasma physics community",
    "Although data science has a long and rich history in plasma physics, dating back at least three decades, it is experiencing a renaissance, thanks in large part to the advances outside of plasma physics.",
    "Emerging data-driven methods could have a transformative effect across the full spectrum of plasma research.",
    "The DPP mini-conference and the articles herein represent only a tiny cross section of contemporary research on data-driven plasma science.",
    "Furthermore, Plasma Science is not unique in its exploration of Scientific Machine Learning: the Second Workshop on Machine Learning and the Physical Sciences (NeurIPS 2019, Vancouver, BC, Canada, December 2019) and it illustrates a trend in cross disciplinary collaboration with contributions from plasma research."
]

# Convert each sentence in text_data to lowercase
text_data = [text.lower() for text in text_data]

# Tokenize words for each sentence
words_list = [word_tokenize(text) for text in text_data]

# Remove stopwords and punctuation for each list of words
stopwords_list = stopwords.words('english') + list(string.punctuation)
cleaned_words_list = [[word for word in words if word not in stopwords_list] for words in words_list]

# Lemmatize words for each list of words
lemmatizer = WordNetLemmatizer()
lemmatized_words_list = [[lemmatizer.lemmatize(word) for word in words] for words in cleaned_words_list]

# Convert lemmatized words to numeric values using CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform([' '.join(words) for words in lemmatized_words_list])
feature_names = vectorizer.get_feature_names_out()

# Placeholder for y: For the sake of example, assigning a dummy y. In reality, this should be your actual labels.
y = [1, 0, 1, 0, 1, 0]  # Example binary labels for each text

# Calculate MI scores
mi_scores = mutual_info_classif(X, y)

# Print MI scores in descending order
sorted_features = sorted(zip(feature_names, mi_scores), key=lambda x: x[1], reverse=True)
for feature, score in sorted_features:
    print(f"{feature}: {score}")


science: 0.4620981203732969
data: 0.3182570841474064
dpp: 0.3182570841474063
learning: 0.23104906018664828
machine: 0.23104906018664828
physic: 0.14384103622589034
plasma: 0.14384103622589034
2018: 0.13230412471889824
2019: 0.13230412471889824
60th: 0.13230412471889824
across: 0.13230412471889824
advance: 0.13230412471889824
also: 0.13230412471889824
although: 0.13230412471889824
american: 0.13230412471889824
aps: 0.13230412471889824
article: 0.13230412471889824
artificial: 0.13230412471889824
back: 0.13230412471889824
bc: 0.13230412471889824
broader: 0.13230412471889824
canada: 0.13230412471889824
collaboration: 0.13230412471889824
community: 0.13230412471889824
contains: 0.13230412471889824
contemporary: 0.13230412471889824
contribution: 0.13230412471889824
could: 0.13230412471889824
dating: 0.13230412471889824
decade: 0.13230412471889824
december: 0.13230412471889824
disciplinary: 0.13230412471889824
division: 0.13230412471889824
effect: 0.13230412471889824
emerging: 0.1323041247188

Question 4 (10 points): Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [17]:
!pip install torch

In [18]:
!pip install scikit-learn

In [19]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 9.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 32.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 43.1 MB/s eta 0:00:00


In [20]:
import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity

# Sample text data
reviews = [
    "Introducing the Graph of Thoughts (GoT): a cutting-edge framework that elevates the prompting capabilities of large language models (LLMs) beyond established paradigms",
    "like Chain-of-Thought or Tree of Thoughts (ToT). GoT's primary innovation lies in its unique ability to represent LLM-generated information as an intricate, unrestricted graph",
    "Here, individual units of information, referred to as 'LLM thoughts,' serve as vertices interconnected by edges, symbolizing the intricate dependencies between them.",
    "This novel approach empowers us to harmoniously blend various LLM thoughts, distilling the essence of complex thought networks, and amplifying ideas through feedback loops. ",
    "GoT showcases its superiority over existing methodologies by significantly enhancing sorting quality by 62% compared to ToT, while concurrently reducing costs by over 31%.",
    "Moreover, GoT has been meticulously designed for extensibility, accommodating the integration of fresh thought transformations",
    "This groundbreaking approach empowers us to harmoniously blend various LLM thoughts, distilling the very essence of complex thought networks, and amplifying ideas through feedback loops, creating a sense of awe and astonishment.🙂 ",
    "Making it an avant-garde platform for pioneering new prompting strategies🙂. This research aims to bridge the gap between LLM reasoning and human thought processes, mirroring the intricate networks observed in phenomena like brain mechanisms and recurrence.",
]

# Query
query = "I'm looking for a relaxing vacation spot with beautiful scenery."

# Load pre-trained BERT model and tokenizer
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# Tokenize and encode the query
query_tokens = tokenizer(query, padding=True, truncation=True, return_tensors="pt")
with torch.no_grad():
    query_output = model(**query_tokens).last_hidden_state.mean(dim=1)

# Calculate cosine similarity between the query and each review
similarities = []
for review in reviews:
    review_tokens = tokenizer(review, padding=True, truncation=True, return_tensors="pt")
    with torch.no_grad():
        review_output = model(**review_tokens).last_hidden_state.mean(dim=1)
    similarity = cosine_similarity(query_output, review_output)
    similarities.append(similarity.item())

# Rank the reviews based on similarity in descending order
ranked_reviews = sorted(zip(reviews, similarities), key=lambda x: x[1], reverse=True)

# Print the ranked reviews
for i, (review, similarity) in enumerate(ranked_reviews, start=1):
    print(f"Rank {i}: Similarity = {similarity:.4f}\nReview: {review}\n")


Rank 1: Similarity = 0.5909
Review: This groundbreaking approach empowers us to harmoniously blend various LLM thoughts, distilling the very essence of complex thought networks, and amplifying ideas through feedback loops, creating a sense of awe and astonishment.🙂 

Rank 2: Similarity = 0.5638
Review: This novel approach empowers us to harmoniously blend various LLM thoughts, distilling the essence of complex thought networks, and amplifying ideas through feedback loops. 

Rank 3: Similarity = 0.5605
Review: like Chain-of-Thought or Tree of Thoughts (ToT). GoT's primary innovation lies in its unique ability to represent LLM-generated information as an intricate, unrestricted graph

Rank 4: Similarity = 0.5510
Review: Here, individual units of information, referred to as 'LLM thoughts,' serve as vertices interconnected by edges, symbolizing the intricate dependencies between them.

Rank 5: Similarity = 0.5339
Review: Introducing the Graph of Thoughts (GoT): a cutting-edge framework tha